name: humble_arm32 build (EOL)

on:
  push:
    branches: [ ros2 ]
  pull_request:
    branches: [ ros2 ]
  workflow_dispatch: 
                            
jobs:
  humble_arm32_build:
    container:
      image: rclex/arm32v7_ros_docker:humble
    runs-on: ubuntu-24.04
    strategy:
        matrix:
          ros_distribution:
            - humble
    steps:

  
        - name: Build and test ROS 2
          uses: ros-tooling/action-ros-ci@v0.3
          with:
            package-name: mocap_nokov
            target-ros2-distro: ${{ matrix.ros_distribution }}
            skip-tests: true
  