name: humble_arm32 build (EOL)

on:
  push:
    branches: [ ros2 ]
  pull_request:
    branches: [ ros2 ]
  workflow_dispatch: 
                            
jobs:
  humble_arm32_build:
    container:
      image: rclex/arm32v7_ros_docker:humble
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - humble
    steps:
      - name: install QEMU
        run: |
          apt install -y qemu qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check container status
        run: docker ps -a

      - name: Install system dependencies
        run: |
          apt update
          apt install -y \
            ros-${{ matrix.ros_distribution }}-geometry-msgs \
            ros-${{ matrix.ros_distribution }}-tf2 \
            ros-${{ matrix.ros_distribution }}-tf2-ros \
            ros-${{ matrix.ros_distribution }}-ament-cmake \
            ros-${{ matrix.ros_distribution }}-ament-lint-auto \
            ros-${{ matrix.ros_distribution }}-ament-lint-common \
            ros-${{ matrix.ros_distribution }}-rclcpp

      - name: Build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: mocap_nokov
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true