name: noetic_arm32 build (EOL)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 

jobs:
  noetic_arm32_build:
    runs-on: ubuntu-22.04
    steps:
      # 安装 QEMU 并启用多架构支持
      - name: Install QEMU
        run: |
          sudo apt update
          sudo apt install -y qemu qemu-user-static
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      # 拉取 ARM 镜像
      - name: Pull Docker image
        run: sudo docker pull --platform linux/arm/v7 arm32v7/ros:noetic

      # 在容器中运行后续步骤
      - name: Run steps in Docker container
        run: |
          sudo docker run --rm -v $GITHUB_WORKSPACE:/workspace arm32v7/ros:noetic /bin/bash -c "
            cd /workspace &&
            ls &&
            source ~/ros2_ws/install/local_setup.bash &&
            mkdir -p ros2_ws/src &&
            cd ros2_ws/src &&
            git clone -b ros2 https://github.com/NOKOV-MOCAP/mocap_nokov.git &&
            cd .. &&
            colcon build --packages-select mocap_nokov
          "