name: melodic build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: 

jobs:
  melodic_build:
    container:
      image: ubuntu:bionic
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    runs-on: ubuntu-latest
    strategy:
        matrix:
          ros_distribution:
            - melodic
    steps:
        - name: Setup ROS environment
          uses: actions/checkout@v1
          with:
            required-ros-distributions: ${{ matrix.ros_distribution }}
        - name: Build and test ROS
          uses: ros-tooling/action-ros-ci@v0.3
          with:
            package-name: mocap_nokov
            target-ros1-distro: ${{ matrix.ros_distribution }}
            skip-tests: true