name: melodic build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: 

jobs:
  melodic_build:
    container:
      image: mesonbuild/bionic:latest
      volumes:
        - /node20217:/node20217
        - /node20217:/__e/node20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - melodic
    steps:
      - name: Install Node.js 20 with glibc 2.17
        run: |
          apt-get update
          apt install -y curl
          curl -LO https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
          tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
          ldd /__e/node20/bin/node  
      - name: cancle preivious run
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Install system dependencies
        run: |
          apt update
          apt install -y \
            ros-${{ matrix.ros_distribution }}-geometry-msgs \
            ros-${{ matrix.ros_distribution }}-tf \
            ros-${{ matrix.ros_distribution }}-nav-msgs \
            ros-${{ matrix.ros_distribution }}-dynamic-reconfigure \
            ros-${{ matrix.ros_distribution }}-roscpp \
            ros-${{ matrix.ros_distribution }}-catkin \
            ros-${{ matrix.ros_distribution }}-roslaunch \
            ros-${{ matrix.ros_distribution }}-roslint
      - name: Build and test ROS
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: mocap_nokov
          target-ros1-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
      


