name: melodic build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: 

jobs:
  melodic_build:
    container:
        image: ubuntu:bionic
    runs-on: ubuntu-latest
    strategy:
        matrix:
          ros_distribution:
            - melodic
    steps:
        - name: Setup ROS environment
          uses: docker/setup-qemu-action@v1
          uses: './'
          env:
            DOCKER_IMAGE: 'arm32v7/ros:melodic-ros-core'
            BEFORE_INIT: '[[ $(uname -p) == armv7l ]] && exit 42'
            EXPECT_EXIT_CODE: 42
          with:
            required-ros-distributions: ${{ matrix.ros_distribution }}
        - name: Build and test ROS
          uses: ros-tooling/action-ros-ci@v0.3
          with:
            package-name: mocap_nokov
            target-ros1-distro: ${{ matrix.ros_distribution }}
            skip-tests: true