name: melodic build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: 

jobs:
  melodic_build:
    name: "Ros Melodic Morenia"
    container:
      image: ubuntu:bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with :
        node-version: '12.x'
    - run: npm ci
    - run: npm run build
    - uses: ./
      with:
        required-ros-distributions: melodic
    - run: test -f /opt/ros/melodic/setup.sh
    