name: noetic build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 
                            
jobs:
  noetic_build:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
          ros_distribution:
            - noetic
    steps:
        - name: Setup ROS environment
          uses: ros-tooling/setup-ros@v0.7
          with:
            required-ros-distributions: ${{ matrix.ros_distribution }}
  
        - name: Install system dependencies
          run: |
            sudo apt update
            sudo apt install -y \
              ros-${{ matrix.ros_distribution }}-geometry-msgs \
              ros-${{ matrix.ros_distribution }}-tf \
              ros-${{ matrix.ros_distribution }}-nav-msgs \
              ros-${{ matrix.ros_distribution }}-dynamic-reconfigure \
              ros-${{ matrix.ros_distribution }}-roscpp \
              ros-${{ matrix.ros_distribution }}-catkin \
              ros-${{ matrix.ros_distribution }}-roslaunch \
              ros-${{ matrix.ros_distribution }}-roslint
        - name: Build and test ROS
          uses: ros-tooling/action-ros-ci@v0.3
          with:
            package-name: mocap_nokov
            target-ros1-distro: ${{ matrix.ros_distribution }}
            skip-tests: true